[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = ["models/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
