[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  external_node_modules = ["express", "mongoose", "jsonwebtoken", "cors", "dotenv"]
  included_files = ["models/*"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
